# Generated by Django 5.2.7 on 2025-10-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabourRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('section', models.CharField(max_length=100)),
                ('sn', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('quarter', 'year', 'section', 'sn', 'description')},
            },
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('section', models.CharField(max_length=100)),
                ('sn', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('quarter', 'year', 'section', 'sn', 'description')},
            },
        ),
    ]
