# Generated by Django 5.2.7 on 2025-10-29 09:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0002_forecast_project_userprofile_report_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='material',
            new_name='material_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='actual_cost',
        ),
        migrations.AddField(
            model_name='project',
            name='cidb_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='inflation_quarter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='inflation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cidb_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cidb_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estimator.project')),
            ],
            options={
                'unique_together': {('project', 'section', 'description')},
            },
        ),
    ]
