# Generated by Django 5.2.7 on 2025-10-30 04:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0003_rename_material_forecast_material_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_file',
            field=models.FileField(blank=True, null=True, upload_to='actual/'),
        ),
        migrations.AddField(
            model_name='project',
            name='inflation_multiplier',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
