# Generated by Django 5.2.7 on 2025-10-31 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0004_project_actual_cost_project_actual_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='actual_file',
        ),
        migrations.AddField(
            model_name='project',
            name='duration_months',
            field=models.IntegerField(blank=True, help_text='Project duration in months', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_items', to='estimator.project'),
        ),
        migrations.CreateModel(
            name='ActualItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_actual', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('rate_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('project_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actual', to='estimator.projectitem')),
            ],
        ),
    ]
