# Generated by Django 5.2.7 on 2025-11-01 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0005_remove_project_actual_file_project_duration_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-filled from start/end', null=True),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='original_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='InflationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimator.project')),
            ],
        ),
    ]
