# Generated by Django 5.2.7 on 2025-11-01 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0006_project_duration_days_projectitem_original_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimator.project'),
        ),
    ]
