# Generated by Django 5.2.7 on 2025-11-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0007_forecast_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='person_in_charge',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
