# Generated by Django 5.2.7 on 2025-11-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0008_project_details_project_person_in_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIDBUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'CIDB Data Upload',
                'verbose_name_plural': 'CIDB Data Upload',
            },
        ),
    ]
